"$schema" = "./node_modules/wrangler/config-schema.json"
name = "discordhook"
main = "index.js"
compatibility_date = "2025-07-13"

[[kv_namespaces]]
binding = "mailbox"
id = "e2ec70d94f644aaea40f86b02e099ca5"


[observability.logs]
enabled = true
