name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v6
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          secrets: |
            POLICY_AUD
            TEAM_DOMAIN
        env:
          POLICY_AUD: ${{ secrets.POLICY_AUD }}
          TEAM_DOMAIN: ${{ secrets.TEAM_DOMAIN }}